name: manually triggered workflows
on:
  workflow_dispatch
jobs:
  test-cmd:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Get current time
      uses: 1466587594/get-current-time@v1
      id: current-date-time
      with:
        format: YYYY-MM-DD
    - name: publish
      env:
        DATE_TIME: "${{ steps.current-date-time.outputs.formattedTime }}" 
      run: |
        echo $GITHUB_ACTOR
